//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hckaton2018v2.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public string apPaterno { get; set; }
        public string apMaterno { get; set; }
        public string direccion { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string cp { get; set; }
        public string genero { get; set; }
        public int idUsuario { get; set; }
        public int idEstado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
