//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hckaton2018v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidato()
        {
            this.pregunta = new HashSet<pregunta>();
            this.propuestas = new HashSet<propuestas>();
        }
    
        public int idCandidato { get; set; }
        public int idPartido { get; set; }
        public int idUsuario { get; set; }
        public int idTipoCandidato { get; set; }
        public int idPresupuesto { get; set; }
    
        public virtual partidoPolitico partidoPolitico { get; set; }
        public virtual presupuesto presupuesto { get; set; }
        public virtual tipoCandidato tipoCandidato { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregunta> pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propuestas> propuestas { get; set; }
    }
}
