//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hckaton2018v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregunta
    {
        public int idPregunta { get; set; }
        public int idCandidato { get; set; }
        public string nombre { get; set; }
        public string pregunta1 { get; set; }
        public Nullable<int> votosPositivos { get; set; }
        public Nullable<int> votosNegativos { get; set; }
        public string respuesta { get; set; }
    
        public virtual candidato candidato { get; set; }
    }
}
