//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hckaton2018v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class propuestas
    {
        public int idPropuesta { get; set; }
        public string descripcion { get; set; }
        public int idTipoPropuesta { get; set; }
        public int idCandidato { get; set; }
        public int idArchivo { get; set; }
    
        public virtual archivo archivo { get; set; }
        public virtual candidato candidato { get; set; }
        public virtual tipoPropuesta tipoPropuesta { get; set; }
    }
}
